### ISSUE TITLE
Code handling

### ISSUE THREAD

**Issue by lf-araujo** [lukas-h/onepage#1]
Dear Lukas,

thanks for the awesome design. 

I have tested it in my blog, however some code snippets flows outside the colored environment. 

See [here](https://lf-araujo.github.io/)

- What am I doing wrong?

**Comment by lukas-h** [comment]
Thank you! 
It's not your fault, I simply haven't included code highlighting. I embed github gists instead.
In my other theme is syntax highlighting integrated

**Comment by lukas-h** [comment]
https://github.com/lukas-h/material-theme

**Comment by lukas-h** [comment]
https://gist.github.com/demisx/025698a7b5e314a7a4b5

**Comment by lf-araujo** [comment]
Amazing Lukas, 

That fixed the problem, thanks! 

Two things though:

1. the space between the lines of the highlighted text is too small, where I can edit that property?
2. the design does not support bullet points? Look at the following passage in the [link](https://lf-araujo.github.io/Yet-Another-CV):


    A working git installation;
    Fira Mono & Minion Pro fonts installed in the system;
    a working pandoc and xelatex installation;
    and the installation of my repo (see below).

It was written with markdown with:

```
-     A working git installation;
-    Fira Mono & Minion Pro fonts installed in the system;
-    a working pandoc and xelatex installation;
-    and the installation of my repo (see below).
```

How to allow support for this kind of markdown?

**Comment by lukas-h** [comment]
```
ul{
    list-style-type: none;
    padding: 0;
}
li{
    display: list-item;
    text-align: -webkit-match-parent;
    list-style-type: none;
    margin: 0;
}
```
You could edit the list styles in assets/css/main.css

https://developer.mozilla.org/de/docs/Web/CSS/list-style

**Comment by lukas-h** [comment]
And you can set the `line-height` CSS attribute for the highlighted text (I think you mean the `code` blocks)

**Comment by lukas-h** [comment]
@lf-araujo are all problems solved?

**Comment by lf-araujo** [comment]
Yep, you helped a lot! Thank you very much!

You can close this issue if you want..

Best,

2017-03-26 21:30 GMT+11:00 Lukas Himsel <notifications@github.com>:
